### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by sangle7** [Deerhound579/ks-killer#11]
V0

- [x] Hook ks-killer into the graduate-killswitches command

Goal:

- [ ] Graduate scope: only within specific project 
    - [ ] allow both project name and project path
-  [ ] Graduate before some date
-  [x] Graduate by ID
-  [ ] Handle inline, function and constant assignment
-  [ ] Look for isActivated where the first param is GUID
-  [ ] Create PR automatically 
-  [ ] Reliability 75%+, measured by successful PRs
-  [ ] Fix known bugs in the issue
 

Need to investigate:

-  [ ] Best way to get an active list of KS?
 

Further action:

-  [ ] Run it in a scheduled pipeline
-  [ ] Partner with KS team to see if we can include ks-killer instructions in the email
